[package]
name = "contracts"
repository.workspace = true
description = "Ranger Vehicle SDK/Runtime 共享 DTO、transport envelope 和 schema 协商类型"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
